mindmap
  root(mindmap)
    (Origins)
      (Long history)
      (Popularisation)
        (British popular psychology author Tony Buzan)
    (Research)
      (On effectivness<br/>and features)
      (On Automatic creation)
        (Uses)
            (This is rounded)
    (Tools)
      (Pen and paper)
      (Mermaid)
    (Research)
      (On effectivness<br/>and features)
      (On Automatic creation)
        (Uses)
            (This is rounded)
    (Research)
      (On effectivness<br/>and features)
      (On Automatic creation)
        (Uses)
            (This is rounded)
    (Research)
      (On effectivness<br/>and features)
      (On Automatic creation)
        (Uses)
            (This is rounded)
